#!/usr/bin/env escript
% ANL:waggle-license
% This file is part of the Waggle Platform.  Please see the file
% LICENSE.waggle.txt for the legal details of the copyright and software
% license.  For more details on the Waggle project, visit:
%          http://www.wa8.gl
% ANL:waggle-license
%% -*- erlang -*-

main(_) ->
  check_syntax("rabbitmq.config"),
  check_syntax("enabled_plugins").

check_syntax(Filename) ->
  io:format(Filename),
  io:format(": ~w~n", [file:eval(Filename)]).
