#!/usr/bin/python3

import subprocess
import os


def call(command):
    cmd = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
    output = cmd.communicate()[0].decode().strip()
    return cmd.returncode, output


def check_starter():
    starter = '/root/waggle_platform_starter'
    if os.path.isfile(starter):
        print('Switching to operation mode...')
        os.remove(starter)
        rc, out = call('waggle-safe-mode')
        if rc == 0:
            print('Switching done')
        else:
            print('Failed to switch to operation mode. Try it later.')
            with open(starter, 'a'):
                os.utime(starter, None)


if __name__ == "__main__":
    try:
        check_starter()
    except Exception as ex:
        print(str(ex))
