#!/usr/bin/python3
import subprocess
import os


def call(command):
    cmd = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
    output = cmd.communicate()[0].decode().strip()
    return cmd.returncode, output


def get_hostname():
    r = subprocess.check_output('hostname').decode().strip()

    if 'SD' in r:
        return 'SD'
    if 'MMC' in r:
        return 'eMMC'
    return ''


def check_starter():
    starter = '/root/waggle_platform_starter'
    if os.path.isfile(starter):
        print('Switching to operation mode...')
        os.remove(starter)

        if get_hostname() == 'SD':
            rc, out = call('waggle-mode-burnin')
        else:
            rc, out = call('waggle-mode-burnin-core')

        if rc == 0:
            print('Switching done')
        else:
            print('Failed to switch to operation mode. Try it later.')
            with open(starter, 'a'):
                os.utime(starter, None)


if __name__ == "__main__":
    try:
        check_starter()
    except Exception as ex:
        print(str(ex))
